language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - JOB="test"

matrix:
  fast_finish: true
  include:
    - rust: nightly
      env: JOB="wasm"
  allow_failures:
    # Not yet implemented.
    - env: JOB="wasm"

script:
  - ./ci/script.sh
