language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - JOB="test"

matrix:
  fast_finish: true
  include:
    - rust: nightly
      env: JOB="wasm"
    # Build and deploy the mdbook guide.
    - rust: stable
      env: JOB="guide"
      before_script:
        - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
        - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.2" mdbook)
        - cargo install-update -a
      script:
        - cd guide && mdbook build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: guide/book
        keep-history: false
        on:
          branch: master

script:
  - ./ci/script.sh
