[workspace]
members = [
  "./analyze",
  "./ir",
  "./opt",
  "./parser",
  "./twiggy",
  "./traits",
  "./wasm-api",
  "./job_runner"
]

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
opt-level = "s"
