[package]
name = "twiggy-analyze"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
license = "Apache-2.0/MIT"

[lib]
path = "./analyze.rs"

[dependencies]
twiggy-ir = { version = "0.1.0", path = "../ir" }
twiggy-opt = { version = "0.1.0", path = "../opt", default-features = false }
twiggy-traits = { version = "0.1.0", path = "../traits" }
