[package]
name = "svelte-ir"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[lib]
path = "./ir.rs"

[dependencies]
cpp_demangle = { version = "0.2.7", default-features = false }
frozen = "1"
petgraph = "0.4.11"
rustc-demangle = "0.1.5"
