[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-parser"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.1.0"

[lib]
path = "./parser.rs"

[dependencies]
parity-wasm = "0.28.0"
twiggy-ir = { version = "0.1.0", path = "../ir" }
twiggy-traits = { version = "0.1.0", path = "../traits" }
