[package]
name = "twiggy-parser"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[lib]
path = "./parser.rs"

[dependencies]
parity-wasm = "0.27.1"
twiggy-ir = { version = "0.1.0", path = "../ir" }
twiggy-traits = { version = "0.1.0", path = "../traits" }
