[package]
name = "svelte-parser"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[lib]
path = "./parser.rs"

[dependencies]
parity-wasm = "0.27.1"
svelte-ir = { version = "0.1.0", path = "../ir" }
svelte-traits = { version = "0.1.0", path = "../traits" }
