[package]
name = "twiggy-traits"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.1"
parity-wasm = "0.27.1"
twiggy-ir = { version = "0.1.0", path = "../ir" }
