[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-traits"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.3.0"

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.3"
gimli = { version = "0.16.1", optional = true }
parity-wasm = "0.35.1"
twiggy-ir = { version = "=0.3.0", path = "../ir" }
csv = "1.0.2"
regex = "1.0.5"

[features]
default = []
dwarf = ["gimli"]
emit_json = []
emit_csv = []
emit_text = []
