[package]
name = "twiggy-traits"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
license = "Apache-2.0/MIT"

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.1"
parity-wasm = "0.28.0"
twiggy-ir = { version = "0.1.0", path = "../ir" }
