name: Deploy Docs

on:
  push:
    branches: [ master ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  docs_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build the book
        run: cd guide && mdbook build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: guide/book
          token: ${{ secrets.GITHUB_TOKEN }}